"""add incident task outbox

Revision ID: 140e2e849366
Revises: 1c4b8e2a9d57
Create Date: 2026-09-20 14:05:26.510398

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '140e2e849366'
down_revision: str | Sequence[str] | None = '1c4b8e2a9d57'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_task_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('task_type', sa.String(length=120), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('causation_id', sa.String(length=128), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('publication_status', sa.String(length=24), server_default='PENDING', nullable=False),
    sa.Column('publish_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("publication_status IN ('PENDING', 'PUBLISHED')", name='ck_incident_task_outbox_publication_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('ix_incident_task_outbox_correlation_id', 'incident_task_outbox', ['correlation_id'], unique=False)
    op.create_index('ix_incident_task_outbox_incident_id', 'incident_task_outbox', ['incident_id'], unique=False)
    op.create_index('ix_incident_task_outbox_pending', 'incident_task_outbox', ['publication_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_incident_task_outbox_task_type'), 'incident_task_outbox', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_task_outbox_task_type'), table_name='incident_task_outbox')
    op.drop_index('ix_incident_task_outbox_pending', table_name='incident_task_outbox')
    op.drop_index('ix_incident_task_outbox_incident_id', table_name='incident_task_outbox')
    op.drop_index('ix_incident_task_outbox_correlation_id', table_name='incident_task_outbox')
    op.drop_table('incident_task_outbox')
    # ### end Alembic commands ###