"""add incident task completion outbox

Revision ID: 1b4f045e1eca
Revises: 140e2e849366
Create Date: 2026-09-22 02:24:03.819588

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1b4f045e1eca'
down_revision: str | Sequence[str] | None = '140e2e849366'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_task_completion_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('publication_status', sa.String(length=24), server_default='PENDING', nullable=False),
    sa.Column('publish_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("publication_status IN ('PENDING', 'PUBLISHED')", name='ck_incident_completion_outbox_publication_status'),
    sa.CheckConstraint("status IN ('Open', 'Investigating', 'Monitoring', 'Resolved')", name='ck_incident_completion_outbox_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('ix_incident_completion_outbox_correlation_id', 'incident_task_completion_outbox', ['correlation_id'], unique=False)
    op.create_index('ix_incident_completion_outbox_incident_id', 'incident_task_completion_outbox', ['incident_id'], unique=False)
    op.create_index('ix_incident_completion_outbox_pending', 'incident_task_completion_outbox', ['publication_status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incident_completion_outbox_pending', table_name='incident_task_completion_outbox')
    op.drop_index('ix_incident_completion_outbox_incident_id', table_name='incident_task_completion_outbox')
    op.drop_index('ix_incident_completion_outbox_correlation_id', table_name='incident_task_completion_outbox')
    op.drop_table('incident_task_completion_outbox')
    # ### end Alembic commands ###