-- =========================================================
-- OPSFLOW POSTGRESQL INITIALIZATION
-- =========================================================
--
-- The official PostgreSQL Docker image automatically creates
-- POSTGRES_DB during first-time cluster initialization.
--
-- OpsFlow additionally requires a physically separate
-- database for automated tests:
--
--     opsflow_test
--
-- The application database and test database must never
-- share state.
--
-- This script executes only during initialization of a new,
-- empty PostgreSQL Docker data volume.
-- =========================================================


\set ON_ERROR_STOP on


-- =========================================================
-- CREATE OPSFLOW TEST DATABASE
-- =========================================================
--
-- Use the configured POSTGRES_USER as the owner rather than
-- hard-coding an owner name.
--
-- current_user is the PostgreSQL role executing this script.
--
-- \gexec executes the CREATE DATABASE statement generated by
-- the SELECT only when opsflow_test does not already exist.
-- =========================================================

SELECT
    'CREATE DATABASE opsflow_test OWNER '
    || quote_ident(current_user)
WHERE NOT EXISTS (
    SELECT
        1
    FROM
        pg_database
    WHERE
        datname = 'opsflow_test'
)
\gexec


-- =========================================================
-- DOCUMENT DATABASE PURPOSE
-- =========================================================

COMMENT ON DATABASE opsflow_test IS
    'Isolated database used by the OpsFlow automated test suite';