"""add incident lifecycle fields and indexes

Revision ID: 6522af6ea656
Revises: 8ad43577d275
Create Date: 2026-09-05 10:40:55.756064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6522af6ea656'
down_revision: Union[str, Sequence[str], None] = '8ad43577d275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('source', sa.String(length=80), server_default='manual', nullable=False))
    op.add_column('incidents', sa.Column('customer_impacting', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('incidents', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_incidents_created_at', 'incidents', ['created_at'], unique=False)
    op.create_index('ix_incidents_service_status', 'incidents', ['service_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incidents_service_status', table_name='incidents')
    op.drop_index('ix_incidents_created_at', table_name='incidents')
    op.drop_column('incidents', 'acknowledged_at')
    op.drop_column('incidents', 'customer_impacting')
    op.drop_column('incidents', 'source')
    # ### end Alembic commands ###
