"""create services table

Revision ID: ae0e5c7c2c2d
Revises: 
Create Date: 2026-09-05 04:50:12.359787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0e5c7c2c2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('Healthy', 'Degraded', 'Critical', name='service_status'), nullable=False),
    sa.Column('uptime', sa.String(length=30), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('last_deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('latency_ms >= 0', name='ck_services_latency_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_index(op.f('ix_services_owner'), 'services', ['owner'], unique=False)
    op.create_index(op.f('ix_services_status'), 'services', ['status'], unique=False)
    op.create_table('service_dependencies',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('dependency_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'dependency_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_dependencies')
    op.drop_index(op.f('ix_services_status'), table_name='services')
    op.drop_index(op.f('ix_services_owner'), table_name='services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
